name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'my_dbt_project'  # This should match the profile name in profiles.yml

# Define your model directories here
model-paths: ["models"]

# Optional: Configure test and documentation directories if needed
test-paths: ["tests"]
analysis-paths: ["analysis"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
# seeds:
#   dbt_project:
#     data:
#       file: aeroplane_model.json